kind: Pod
apiVersion: v1
metadata: 
   name: firstpod
   labels: 
     app: sp
     release : stable   
     team: red
   annotations:     
spec: 
 containers:
   - name: db
     image: redis
   - name : web
     image : httpd  
