apiVersion: v1
kind: Service
metadata: 
    name : webserversvc
spec: 
    type: NodePort
    ports:
        - nodePort : 30123
          port: 80
          targetPort: 80
          protocol: TCP
    selector:
          app: httpd      
