apiVersion: v1
kind: Service
metadata: 
    name : docker-mysql
    labels:
        app: docker-mysql
spec: 
    type: NodePort
    ports:
        - nodePort : 30287
          port: 3306
          targetPort: 3306
          protocol: TCP
    selector:
          app: docker-mysql      
