apiVersion: v1
kind: Service
metadata:    
    name: product-app 
    labels:     
        app: product-app 
spec: 
    type: NodePort
    ports:
        - nodePort : 30289
          port: 9090
          targetPort: 9090         
    selector:
          app: product-app 
